### ISSUE TITLE
Add Ping Pong Game 

### ISSUE THREAD

**Issue by thesohailjafri** [thesohailjafri/cpp-games#1]
Pong game is a two-player table tennis-themed video game. The game involves two paddles and a moving ball. The players have to move paddles in an upwards or downwards direction and save the ball from getting hit onto the wall. If the ball hits the wall then it’s a score for another player.

**Direction to play:**

To Start the Game Press the “ENTER” key.
Player 1: Player 1 can control the left side paddle i.e, PADDLE_1 by using the ‘W‘ key to move upwards and to go downwards ‘S‘ key should be used.
Player 2: Player 2 can control the left side paddle i.e, PADDLE_2 by using the ‘UP Arrow‘ key to move upwards and to go downwards ‘Down Arrow‘ key should be used.

**Comment by muntzar313** [comment]
Yes !!
