### ISSUE TITLE
Add Quiz Game

### ISSUE THREAD

**Issue by thesohailjafri** [thesohailjafri/cpp-games#2]
Create a program that will read in a quiz provided and will then give the quiz to a user keeping track of how many questions they get right and how many they get incorrect. Regardless of whether the answer is correct or wrong the next question should be asked immediately afterwards.

**Comment by muntzar313** [comment]
Yes Let's Try to solve this issues #1 # @thesohailjafri

**Comment by muntzar313** [comment]
# Yes Let's Solve This

**Comment by muntzar313** [comment]
Assign this to me i will do it

**Comment by thesohailjafri** [comment]
> Assign this to me i do it

Assigned

**Comment by muntzar313** [comment]
[Quiz-Game.zip](https://github.com/thesohailjafri/cpp-games/files/9692453/Quiz-Game.zip)
